import { ICreditApplicaiton } from './credit-application.interface';

export function creditApplicationInitialState(): ICreditApplicaiton {
  return {
    wayOfApplying: null,
    primary: {
      firstName: '',
      mi: '',
      lastName: '',
      phoneNumber: '',
      emailAddress: '',
      dateOfBirth: null,
      residenceType: null,
      mortage: '',
      streetAddress: '',
      apt: '',
      city: '',
      state: '',
      zipCode: '',
      employerName: '',
      employerAddress: '',
      employerPhone: '',
      securityNumber: '',
      confirmSecurityNumber: '',
      driverLicenseState: '',
      driverLicenseNumber: '',
      grossIncome: '',
    },
    co: {
      firstName: '',
      mi: '',
      lastName: '',
      phoneNumber: '',
      emailAddress: '',
      dateOfBirth: null,
      residenceType: null,
      mortage: '',
      streetAddress: '',
      apt: '',
      city: '',
      state: '',
      zipCode: '',
      employerName: '',
      employerAddress: '',
      employerPhone: '',
      securityNumber: '',
      confirmSecurityNumber: '',
      driverLicenseState: '',
      driverLicenseNumber: '',
      grossIncome: '',
    },
  };
}
